services:
  postgres:
    image: postgres
    container_name: betting_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: betting
    ports:
      - "5433:5432"
    volumes:
      - betting_pg_data:/var/lib/postgresql/data

volumes:
  betting_pg_data:
